### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by robla** [aaron11496/github-wiki-to-phriction#1]
This looks like really intriguing work.  I had struggling a little bit with HTML->Phab cut-and-paste, and came into your converter.  I haven't tried it yet, but I'm already a pandoc user, so it comforts me that you're using pandoc for this.  Also, Wikimedia sites (e.g. Wikipedia) use Lua as the primary templating language.  So, we have all sorts of Lua expertise in our community, not to mention wikitext parsing expertise.

Before I encourage others at Wikimedia to collaborate on your work, though, I'd need to be comfortable that the licensing is clear on this.  Your work seems to be in the proud Github tradition of "publish the source code, and worry about the licensing later"  :-)  Have you thought about a license on your code?

**Comment by aviv-clover** [comment]
Yes, please add license information, so we can fork/contribute...

**Comment by robla** [comment]
> Yes, please add license information, so we can fork/contribute...

Unfortunately, legally speaking, I can't, nor can anyone else, really.  [This page gives a good summary](http://docs.python-guide.org/en/latest/writing/license/):

> Your source publication _needs_ a license. In the US, if no license is specified, users have no legal right to download, modify, or distribute. Furthermore, people can’t contribute to your code unless you tell them what rules to play by.

 [That page from the python-guide](http://docs.python-guide.org/en/latest/writing/license/) gives the clearest advise I've read, but [the Github blog](https://github.com/blog/1530-choosing-an-open-source-license) also gives advice on how to handle this.

Is your intention for your code to be licensed the way [Pandoc itself is licensed (GPLv2)](https://github.com/jgm/pandoc/blob/master/COPYRIGHT) or did you want to pick a different license?

**Comment by aaron11496** [comment]
Sorry for the delay; I was `Not watching` this project for some reason. I added an MIT license so feel free to use the code or contact me if you have more questions.

**Comment by aviv-clover** [comment]
:+1:
