### ISSUE TITLE
What is srp.html and where does it come from

### ISSUE THREAD

**Issue by mydeveloperday** [aaron11496/github-wiki-to-phriction#5]
https://github.com/aaron11496/github-wiki-to-phriction/blob/046c2e0ea390138a5a7190f39b0d96a5defa5466/wiki-migrate.py#L51

Could you add to the readme where srp.html comes from otherwise on running I get

Traceback (most recent call last):
  File "wiki-migrate.py", line 117, in <module>
    main()
  File "wiki-migrate.py", line 43, in main
    fix(phab_url, api_token)
  File "wiki-migrate.py", line 51, in fix
    with open('srp.html') as f:
IOError: [Errno 2] No such file or directory: 'srp.html'
root@jabba29:/opt/pandoc/github-wiki-to-phriction#

**Comment by aaron11496** [comment]
I'm pretty sure that it's the source of the Phriction Search Results Page if you search for all documents. That can be downloaded manually. That function relies on certain css selectors to work but the template of the SRP may have changed by now.

Sorry I can't do any dev on this project now but I could review a PR.
